### PR TITLE
Made businessService filterable

### LINKED ISSUE #13: [TACKLE-8] Make business service a filterable field

### PR DESCRIPTION
**Pull request by mrizzi**
resolve #13

### CODE REVIEW

**Review by carlosthe19916 — COMMENTED** [review]
@mrizzi  I think `@Filterable` is not applicable to this case; as I understand the logic behind the `@Filterable` is to create a `LIKE` query as it is written here https://github.com/konveyor/tackle-commons-rest/blob/main/commons-rest/src/main/java/io/tackle/commons/resources/query/QueryBuilder.java#L104 

The query applicable to `businessService` should be an `EQUALs` and not `LIKE`. Here is one case:

- There are 3 business services with ids `1` and `11` and `111`.
- There are 3 applications associated with each businessService described above: `application[1]=>businessService[1]`, `application[2]=>businessService[11]`, and `application[3]=>businessService[111]`
- The UI tries to filter all applications associated with the businessService whose Id is `1`
- The query to filter will be something like `/application?businessService=1`

From the example above:
- The expected result should be an array with only the application1 since it is the only one associated with businessService[id=1]
- If the `LIKE` operator is applied then the result will contain application1,application2,application3 since all of them will match the criteria.

Maybe I'm missing something in the logic behind `@Filterable`, could you please confirm we won't have the problem described in my example above?

**Comment by mrizzi** [comment]
@carlosthe19916 I can only confirm the problem is well spotted and I think you understood why we were so concerned from this filter and trying to have it done sooner rather than later.
As you suggested in a DM, maybe the time has come to improve filtering capabilities.

**Comment by mrizzi** [comment]
depends on https://github.com/konveyor/tackle-commons-rest/pull/35

**Review by carlosthe19916 — APPROVED** [review]
I've verified again the last changes that includes https://github.com/konveyor/tackle-commons-rest/pull/35 and also the container image @mrizzi shared with me in a DM. This PR looks good to me, thanks @mrizzi for this PR.

**Pull request merged**
